ALTER TABLE FACTURE
DROP CONSTRAINT FK_FAC_LIG;
ALTER TABLE FACTURE
ADD CONSTRAINT FK_FAC_LIG FOREIGN KEY(NumCompteLigue) REFERENCES LIGUE(NumCompteLigue);

ALTER TABLE LIGNE_FACTURE
DROP CONSTRAINT FK_LIF_FAC;
ALTER TABLE LIGNE_FACTURE
ADD CONSTRAINT FK_LIF_FAC FOREIGN KEY(NumFacture) REFERENCES FACTURE(NumFacture);

ALTER TABLE LIGNE_FACTURE
DROP CONSTRAINT FK_LIF_PRE;
ALTER TABLE LIGNE_FACTURE
ADD CONSTRAINT FK_LIF_PRE FOREIGN KEY(CodePrestation) REFERENCES PRESTATION(CodePrestation);

ALTER TABLE LIGUE
DROP CONSTRAINT FK_TRE_LIG;
ALTER TABLE LIGUE
ADD CONSTRAINT FK_TRE_LIG FOREIGN KEY(Tresorier) REFERENCES TRESORIER(Tresorier);