DROP TABLE IF EXISTS LIGUE;
DROP TABLE IF EXISTS PRESTATION;
DROP TABLE IF EXISTS FACTURE;
DROP TABLE IF EXISTS LIGUE_FACTURE;

CREATE TABLE LIGUE
(NumCompteLigue INTEGER NOT NULL,
Intitule VARCHAR(50),
Tresorier VARCHAR(25),
CONSTRAINT PK_LIG PRIMARY KEY (NumCompteLigue)
)ENGINE = INNODB;

CREATE TABLE PRESTATION
(CodePrestation CHAR(20) NOT NULL,
Libelle VARCHAR(30),
Prix_uni DECIMAL(5,3),
CONSTRAINT PK_PRE PRIMARY KEY (CodePrestation)
)ENGINE = INNODB;

CREATE TABLE FACTURE
(NumFacture VARCHAR(7) NOT NULL,
NumCompteLigue INTEGER,
DateFacture DATE,
Echeance DATE,
CONSTRAINT PK_FAC PRIMARY KEY (NumFacture)
)ENGINE = INNODB;

CREATE TABLE LIGNE_FACTURE
(NumFacture VARCHAR(7) NOT NULL,
CodePrestation CHAR(20) NOT NULL,
Quantite INTEGER,
CONSTRAINT PK_LFA PRIMARY KEY (NumFacture,CodePrestation)
)ENGINE  = INNODB;

CREATE TABLE TRESORIER
(Tresorier VARCHAR(25),
AdressePerso VARCHAR(50),
CONSTANT PK_TRE PRIMARY KEY (Tresorier)
)ENGINE = INNODB;
